general:
  project_name: example
camera_settings:
  exposure_auto: false
  exposure_time: 90000.0
  gain_auto: false
  gain_level: 10.5
  gamma: 0.8
  balance_ratio_red: 1.58
  balance_ratio_blue: 1.79
  black_level: 0.0
scanner_settings:
  x_min: 0.0
  x_max: 400.0
  x_step: 50.0
  y_min: 0.0
  y_max: 1600.0
  y_step: 80.0
  z_min: -30000.0
  z_max: -10000.0
  z_step: 1500.0
stacking:
  stack_images: true
  stacking_method: default
  threshold: 7.5
  display_focus_check: false
  additional_sharpening: false
masking:
  mask_images: true
  mask_thresh_min: 195
  mask_thresh_max: 254
  min_artifact_size_black: 1000
  min_artifact_size_white: 2000
exif_data:
  Make: FLIR
  Model: BFS-U3-200S6C-C
  SerialNumber: 18382947
  Lens: MPZ
  CameraSerialNumber: 18382947
  LensManufacturer: Computar
  LensModel: 35.0 f/2.2
  FocalLength: 35.0
  FocalLengthIn35mmFormat: 95.0
